// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umnmwvpdvsflczqeileb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbm13dnBkdnNmbGN6cWVpbGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjIzMzksImV4cCI6MjA3MzgzODMzOX0.oLfDCWrZLT3DMc54AcfQphOxewMPXGfU_joMdHhKx9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});